# version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wms
      MYSQL_USER: wms
      MYSQL_PASSWORD: wms
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbit-data:/var/lib/rabbitmq

  # redis:
  #   image: redis:7
  #   ports:
  #     - '6379:6379'

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   restart: unless-stopped
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #   ports:
  #     - '8081:8081'
  #   depends_on:
  #     - redis
  #   networks:
  #     - wms-net

volumes:
  mysql-data:
  rabbit-data:

networks:
  wms-net:
    driver: bridge
